if not EXIST "Contra (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Contra (U) [!].nes"
if not EXIST "436a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/436a.png"
if not EXIST "Teenage Mutant Hero Turtles - Tournament Fighters (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/gd/Teenage Mutant Hero Turtles - Tournament Fighters (E) [!].nes"
if not EXIST "2254a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/gd/2254a.png"
if not EXIST "Contra (+4 menu).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Contra (+4 menu).nes"
if not EXIST "910a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/910a.png"
if not EXIST "Teenage Mutant Ninja Turtles - Tournament Fighters (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/gd/Teenage Mutant Ninja Turtles - Tournament Fighters (U) [!].nes"
if not EXIST "2259a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/gd/2259a.png"
if not EXIST "Contra Force (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Contra Force (U) [!].nes"
if not EXIST "437a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/437a.png"
if not EXIST "Bikkuri Nekketsu Shin Kiroku! - Harukanaru Kin Medal (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Bikkuri Nekketsu Shin Kiroku! - Harukanaru Kin Medal (J) [!].nes"
if not EXIST "255a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/255a.png"
if not EXIST "Takahashi Meijin no Bouken Shima (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Takahashi Meijin no Bouken Shima (J) [!].nes"
if not EXIST "1001a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1001a.png"
if not EXIST "Crash 'n the Boys - Street Challenge (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Crash 'n the Boys - Street Challenge (U) [!].nes"
if not EXIST "4711a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/4711a.png"
if not EXIST "Hudson's Adventure Island (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Hudson's Adventure Island (U) [!].nes"
if not EXIST "1001a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1001a.png"
if not EXIST "Takahashi Meijin no Bouken Shima II (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Takahashi Meijin no Bouken Shima II (J) [!].nes"
if not EXIST "3177.png" wget --no-check-certificate "https://img.1990i.com/fcpic/3177.png"
if not EXIST "Hudson's Adventure Island II (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Hudson's Adventure Island II (U) [!].nes"
if not EXIST "2581a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2581a.png"
if not EXIST "Nekketsu Kakutou Densetsu (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nekketsu Kakutou Densetsu (J) [!].nes"
if not EXIST "1544a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1544a.png"
if not EXIST "Takahashi Meijin no Bouken Shima III (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Takahashi Meijin no Bouken Shima III (J) [!].nes"
if not EXIST "3179.png" wget --no-check-certificate "https://img.1990i.com/fcpic/3179.png"
if not EXIST "Downtown - Nekketsu Monogatari (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Downtown - Nekketsu Monogatari (J).nes"
if not EXIST "577a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/577a.png"
if not EXIST "Hudson's Adventure Island III (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Hudson's Adventure Island III (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Street Gangs (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Street Gangs (E) [!].nes"
if not EXIST "2114a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2114a.png"
if not EXIST "Takahashi Meijin no Bouken Shima IV (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Takahashi Meijin no Bouken Shima IV (J).nes"
if not EXIST "3181.png" wget --no-check-certificate "https://img.1990i.com/fcpic/3181.png"
if not EXIST "River City Ransom (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/River City Ransom (U) [!].nes"
if not EXIST "1810a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1810a.png"
if not EXIST "Nekketsu Kouha - Kunio-kun (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nekketsu Kouha - Kunio-kun (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Renegade (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Renegade (U) [!].nes"
if not EXIST "2230a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2230a.png"
if not EXIST "Nekketsu! Street Basket - Ganbare Dunk Heroes (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nekketsu! Street Basket - Ganbare Dunk Heroes (J).nes"
if not EXIST "1548a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1548a.png"
if not EXIST "Nekketsu Koukou Dodgeball Bu - Soccer Hen (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nekketsu Koukou Dodgeball Bu - Soccer Hen (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Nintendo World Cup (E) (PRG0) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nintendo World Cup (E) (PRG0) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Nintendo World Cup (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nintendo World Cup (U) [!].nes"
if not EXIST "1587a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1587a.png"
if not EXIST "Kunio-kun no Nekketsu Soccer League (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Kunio-kun no Nekketsu Soccer League (J) [!].nes"
if not EXIST "1223a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1223a.png"
if not EXIST "Nekketsu Koukou Dodgeball Bu (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Nekketsu Koukou Dodgeball Bu (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Super Dodge Ball (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Super Dodge Ball (U) [!].nes"
if not EXIST "2142a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2142a.png"
if not EXIST "Double Dragon (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Double Dragon (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon (E) [!].nes"
if not EXIST "558a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/558a.png"
if not EXIST "Double Dragon (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon (U) [!].nes"
if not EXIST "560a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/560a.png"
if not EXIST "Double Dragon II - The Revenge (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon II - The Revenge (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Double Dragon II - The Revenge (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon II - The Revenge (E) [!].nes"
if not EXIST "564a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/564a.png"
if not EXIST "Double Dragon II - The Revenge (U) (PRG1) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon II - The Revenge (U) (PRG1) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Double Dragon III - The Rosetta Stone (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon III - The Rosetta Stone (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Double Dragon III - The Sacred Stones (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon III - The Sacred Stones (E) [!].nes"
if not EXIST "568a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/568a.png"
if not EXIST "Double Dragon III - The Sacred Stones (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Double Dragon III - The Sacred Stones (U) [!].nes"
if not EXIST "568a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/568a.png"
if not EXIST "Target - Renegade (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Target - Renegade (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Takahashi Meijin no Bugutte Honey (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Takahashi Meijin no Bugutte Honey (J) [!].nes"
if not EXIST "2217a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2217a.png"
if not EXIST "Saiyuuki World (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Saiyuuki World (J).nes"
if not EXIST "1880a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1880a.png"
if not EXIST "Saiyuuki World 2 - Tenjoukai no Majin (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Saiyuuki World 2 - Tenjoukai no Majin (J).nes"
if not EXIST "1881a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1881a.png"
if not EXIST "Snow Bros. (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Snow Bros. (J).nes"
if not EXIST "2023a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2023a.png"
if not EXIST "Whomp'Em (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Whomp'Em (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Super Mario Bros. (W) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Super Mario Bros. (W) [!].nes"
if not EXIST "2146a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2146a.png"
if not EXIST "Super Mario USA (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Super Mario USA (J) [!].nes"
if not EXIST "2161a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2161a.png"
if not EXIST "Super Mario Bros. 2 (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Super Mario Bros. 2 (E) [!].nes"
if not EXIST "2153a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2153a.png"
if not EXIST "Super Mario Bros. 3 (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Super Mario Bros. 3 (E) [!].nes"
if not EXIST "2157a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2157a.png"
if not EXIST "Battle City (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Battle City (J) [!].nes"
if not EXIST "timg.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/timg.png"
if not EXIST "Super Mario Bros. 3 (U) (PRG1) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Super Mario Bros. 3 (U) (PRG1) [!].nes"
if not EXIST "2157a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2157a.png"
if not EXIST "Mario is Missing! (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Mario is Missing! (E) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Mario is Missing! (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Mario is Missing! (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Mario's Time Machine! (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Mario's Time Machine! (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "smb2j.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/smb2j.nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Teenage Mutant Ninja Turtles (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Ninja Turtles (J).nes"
if not EXIST "2257a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2257a.png"
if not EXIST "Teenage Mutant Ninja Turtles II - The Arcade Game (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Ninja Turtles II - The Arcade Game (U) [!].nes"
if not EXIST "2260a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2260a.png"
if not EXIST "Teenage Mutant Ninja Turtles 2 - The Manhattan Project (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Ninja Turtles 2 - The Manhattan Project (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Gekikame Ninja Den (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Gekikame Ninja Den (J).nes"
if not EXIST "838a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/838a.png"
if not EXIST "Teenage Mutant Ninja Turtles (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Ninja Turtles (U) [!].nes"
if not EXIST "2258a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2258a.png"
if not EXIST "Teenage Mutant Hero Turtles - Tournament Fighters (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Hero Turtles - Tournament Fighters (E) [!].nes"
if not EXIST "2254a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2254a.png"
if not EXIST "Teenage Mutant Ninja Turtles - Tournament Fighters (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Teenage Mutant Ninja Turtles - Tournament Fighters (U) [!].nes"
if not EXIST "2259a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2259a.png"
if not EXIST "Battletoads & Double Dragon - The Ultimate Team (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Battletoads & Double Dragon - The Ultimate Team (E) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Battletoads & Double Dragon - The Ultimate Team (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Battletoads & Double Dragon - The Ultimate Team (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Son Son (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Son Son (J) [!].nes"
if not EXIST "2045a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2045a.png"
if not EXIST "Mighty Final Fight (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Mighty Final Fight (J) [!].nes"
if not EXIST "1455a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1455a.png"
if not EXIST "Mighty Final Fight (U) [T+Chi].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Mighty Final Fight (U) [T+Chi].nes"
if not EXIST "1456a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1456a.png"
if not EXIST "宇宙战将(最终幻想2).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/宇宙战将(最终幻想2).nes"
if not EXIST "FC_5132.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5132.gif"
if not EXIST "Final Fantasy (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Final Fantasy (J).nes"
if not EXIST "FC_5134.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5134.gif"
if not EXIST "[NJ063] Final Fantasy VII.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ063] Final Fantasy VII.nes"
if not EXIST "FC_5151.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5151.gif"
if not EXIST "FF1E.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/FF1E.nes"
if not EXIST "FC_5153.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5153.gif"
if not EXIST "[ES-1078] Ge Lan Di Ya (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[ES-1078] Ge Lan Di Ya (C).nes"
if not EXIST "FC_5159.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5159.gif"
if not EXIST "Meng Huan (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Meng Huan (C).nes"
if not EXIST "FC_5161.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5161.gif"
if not EXIST "Shui Hu Shen Shou (NJ019) (Ch).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Shui Hu Shen Shou (NJ019) (Ch).nes"
if not EXIST "FC_5172.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5172.gif"
if not EXIST "混沌世界.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/混沌世界.nes"
if not EXIST "FC_5177.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5177.gif"
if not EXIST "Yu-Gi-Oh (NJ032) (Ch) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Yu-Gi-Oh (NJ032) (Ch) [!].nes"
if not EXIST "FC_5179.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5179.gif"
if not EXIST "[NJ081] Huo Ying Ren Zhe (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ081] Huo Ying Ren Zhe (C).nes"
if not EXIST "FC_5180.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5180.gif"
if not EXIST "36J.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/36J.nes"
if not EXIST "FC_4929.jpg" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4929.jpg"
if not EXIST "[NJ095] Qi Long Zhu Da Mao Xian (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ095] Qi Long Zhu Da Mao Xian (C).nes"
if not EXIST "FC_4931.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4931.gif"
if not EXIST "生化危机.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/生化危机.nes"
if not EXIST "FC_5187.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5187.gif"
if not EXIST "[ES-1071] 三侠五义 (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[ES-1071] 三侠五义 (C).nes"
if not EXIST "FC_4932.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4932.gif"
if not EXIST "samurai_ii_rpg(c).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/samurai_ii_rpg(c).nes"
if not EXIST "FC_5190.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5190.gif"
if not EXIST "Sanada Juu Yuushi (ES-1102)(Ch).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Sanada Juu Yuushi (ES-1102)(Ch).nes"
if not EXIST "FC_5193.png" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5193.png"
if not EXIST "San Guo Zhi - CaoCao Zhuan (NJ018) (Ch).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/San Guo Zhi - CaoCao Zhuan (NJ018) (Ch).nes"
if not EXIST "FC_4938.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4938.gif"
if not EXIST "XAJH.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/XAJH.nes"
if not EXIST "FC_5199.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5199.gif"
if not EXIST "San Guo Wu Shuang - Meng Jiang Zhuan (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/San Guo Wu Shuang - Meng Jiang Zhuan (C).nes"
if not EXIST "FC_4952.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4952.gif"
if not EXIST "ylqxz.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/ylqxz.nes"
if not EXIST "FC_5208.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5208.gif"
if not EXIST "Gen Ke Le Zhuan (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Gen Ke Le Zhuan (C).nes"
if not EXIST "FC_5214.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5214.gif"
if not EXIST "Hu Lu Jin Gang (NJ039) (Ch) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Hu Lu Jin Gang (NJ039) (Ch) [!].nes"
if not EXIST "FC_5216.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5216.gif"
if not EXIST "无双大蛇之三国大乱斗.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/无双大蛇之三国大乱斗.nes"
if not EXIST "FC_4962.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4962.gif"
if not EXIST "everquest(C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/everquest(C).nes"
if not EXIST "FC_5227.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5227.gif"
if not EXIST "[NJ072] Feng Yin Dao.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ072] Feng Yin Dao.nes"
if not EXIST "FC_4972.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4972.gif"
if not EXIST "Metal Max.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Metal Max.nes"
if not EXIST "FC_5232.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5232.gif"
if not EXIST "pal_I.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/pal_I.nes"
if not EXIST "FC_4977.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4977.gif"
if not EXIST "侠客情-荆轲刺秦王.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/侠客情-荆轲刺秦王.nes"
if not EXIST "FC_4979.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4979.gif"
if not EXIST "DQ2C.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/DQ2C.nes"
if not EXIST "FC_4985.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4985.gif"
if not EXIST "Yong Ze Do Re Long 6 (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Yong Ze Do Re Long 6 (C).nes"
if not EXIST "FC_4987.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4987.gif"
if not EXIST "勇者斗恶龙4中文版.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/勇者斗恶龙4中文版.nes"
if not EXIST "FC_4990.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4990.gif"
if not EXIST "Dragon Quest VIII (C)[!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Dragon Quest VIII (C)[!].nes"
if not EXIST "FC_4997.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_4997.gif"
if not EXIST "PockMonRed(C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/PockMonRed(C).nes"
if not EXIST "FC_5004.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5004.gif"
if not EXIST "口袋妖怪金.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/口袋妖怪金.nes"
if not EXIST "FC_5005.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5005.gif"
if not EXIST "Jin Yong Qun Xia Zhuan - Shu Jian Jiang Shan (NJ031) (Ch).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Jin Yong Qun Xia Zhuan - Shu Jian Jiang Shan (NJ031) (Ch).nes"
if not EXIST "FC_5261.png" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5261.png"
if not EXIST "Kou Dai Yao Guai - Shui Jing Ban (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Kou Dai Yao Guai - Shui Jing Ban (C).nes"
if not EXIST "FC_5008.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5008.gif"
if not EXIST "Lei Dian Huang Bi Ka Qiu Chuan Shuo (NJ046) (Ch) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Lei Dian Huang Bi Ka Qiu Chuan Shuo (NJ046) (Ch) [!].nes"
if not EXIST "FC_5012.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5012.gif"
if not EXIST "hero_on_devil_lands(C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/hero_on_devil_lands(C).nes"
if not EXIST "FC_5271.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5271.gif"
if not EXIST "ZZZ_UNK_destiny_of_an_emperor (262289).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/ZZZ_UNK_destiny_of_an_emperor (262289).nes"
if not EXIST "FC_5016.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5016.gif"
if not EXIST "Mo Jie Ta Shi (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Mo Jie Ta Shi (C).nes"
if not EXIST "FC_5274.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5274.gif"
if not EXIST "moshenfashicn.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/moshenfashicn.nes"
if not EXIST "FC_5276.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5276.gif"
if not EXIST "黄金的太阳.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/黄金的太阳.nes"
if not EXIST "FC_5280.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5280.gif"
if not EXIST "Dragon Ball Z 2 - Gekishin Freeza! (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Dragon Ball Z 2 - Gekishin Freeza! (C).nes"
if not EXIST "FC_5284.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5284.gif"
if not EXIST "Dragon Ball Z Gaiden - Saiya Jin Zetsumetsu Keikaku (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Dragon Ball Z Gaiden - Saiya Jin Zetsumetsu Keikaku (C).nes"
if not EXIST "FC_5285.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5285.gif"
if not EXIST "Ne Zha Chuan Qi (NJ036) (Ch) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Ne Zha Chuan Qi (NJ036) (Ch) [!].nes"
if not EXIST "FC_5063.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5063.gif"
if not EXIST "[NJ069] Tang Bo Hu Dian Qiu Xiang.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ069] Tang Bo Hu Dian Qiu Xiang.nes"
if not EXIST "FC_5064.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5064.gif"
if not EXIST "Huan Shi Lu (NJ034) (Ch) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Huan Shi Lu (NJ034) (Ch) [!].nes"
if not EXIST "FC_5104.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5104.gif"
if not EXIST "digital_dragon(C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/digital_dragon(C).nes"
if not EXIST "FC_5119.gif" wget --no-check-certificate "https://img.1990i.com/fcpic/jsbyzw/FC_5119.gif"
if not EXIST "Kaiketsu Yanchamaru 2 - Karakuri Land (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Kaiketsu Yanchamaru 2 - Karakuri Land (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Dragon Ball - Shen Long no Nazo (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Dragon Ball - Shen Long no Nazo (J).nes"
if not EXIST "588a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/588a.png"
if not EXIST "Super Spy Hunter (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Super Spy Hunter (U) [!].nes"
if not EXIST "2180a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2180a.png"
if not EXIST "Battleship (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Battleship (U) [!].nes"
if not EXIST "223a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/223a.png"
if not EXIST "Punch-Out!! (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Punch-Out!! (J).nes"
if not EXIST "1737a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1737a.png"
if not EXIST "Touch Down Fever (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Touch Down Fever (U) [!].nes"
if not EXIST "2352a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2352a.png"
if not EXIST "Impartial Judge (Unl).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Impartial Judge (Unl).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Kaiketsu Yanchamaru 3 - Taiketsu! Zouringen (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Kaiketsu Yanchamaru 3 - Taiketsu! Zouringen (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Dragon Power (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Dragon Power (U) [!].nes"
if not EXIST "600a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/600a.png"
if not EXIST "BreakThru (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/BreakThru (U) [!].nes"
if not EXIST "301a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/301a.png"
if not EXIST "Solomon no Kagi (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Solomon no Kagi (J).nes"
if not EXIST "2035a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2035a.png"
if not EXIST "Mike Tyson's Punch-Out!! (U) (PRG0) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Mike Tyson's Punch-Out!! (U) (PRG0) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Quarter Back Scramble (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Quarter Back Scramble (J).nes"
if not EXIST "1757a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1757a.png"
if not EXIST "Shi Kong Zhi Lun (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Shi Kong Zhi Lun (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Monster Party (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Monster Party (U) [!].nes"
if not EXIST "1512a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1512a.png"
if not EXIST "Rolling Thunder (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Rolling Thunder (J) [!].nes"
if not EXIST "1860a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1860a.png"
if not EXIST "Solomon's Key (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Solomon's Key (E) [!].nes"
if not EXIST "2037a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2037a.png"
if not EXIST "US Championship V'Ball (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/US Championship V'Ball (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Soccer League - Winner's Cup (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Soccer League - Winner's Cup (J).nes"
if not EXIST "2030a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2030a.png"
if not EXIST "STARTRO2.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/STARTRO2.nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Darkwing Duck (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Darkwing Duck (E) [!].nes"
if not EXIST "482a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/482a.png"
if not EXIST "1942 (JU) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/1942 (JU) [!].nes"
if not EXIST "5a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/5a.png"
if not EXIST "Rolling Thunder (Tengen) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Rolling Thunder (Tengen) [!].nes"
if not EXIST "1860a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1860a.png"
if not EXIST "Solomon's Key (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Solomon's Key (U) [!].nes"
if not EXIST "2038a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2038a.png"
if not EXIST "Super Spike V'Ball (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Super Spike V'Ball (U) [!].nes"
if not EXIST "2173a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2173a.png"
if not EXIST "John Elway's Quarterback (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/John Elway's Quarterback (U) [!].nes"
if not EXIST "1110a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1110a.png"
if not EXIST "Xing Zhan Qing Yuan (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Xing Zhan Qing Yuan (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Darkwing Duck (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Darkwing Duck (U) [!].nes"
if not EXIST "482a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/482a.png"
if not EXIST "1943 - The Battle of Valhalla (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/1943 - The Battle of Valhalla (J) [!].nes"
if not EXIST "8a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/8a.png"
if not EXIST "Rolling Thunder (Tengen) [T+Chi_Kamming].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Rolling Thunder (Tengen) [T+Chi_Kamming].nes"
if not EXIST "1860a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1860a.png"
if not EXIST "Solomon no Kagi 2 - Coolmin Tou Kyuushutsu Sakusen (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Solomon no Kagi 2 - Coolmin Tou Kyuushutsu Sakusen (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Volleyball (UE) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Volleyball (UE) [!].nes"
if not EXIST "2424a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2424a.png"
if not EXIST "Super Rugby (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Super Rugby (J) [!].nes"
if not EXIST "2171a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2171a.png"
if not EXIST "Xing He Zhan Shi (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Xing He Zhan Shi (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Devil Man (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Devil Man (J).nes"
if not EXIST "519a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/519a.png"
if not EXIST "1943 - The Battle of Midway (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/1943 - The Battle of Midway (U) [!].nes"
if not EXIST "7a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/7a.png"
if not EXIST "Juuryoku Soukou Metal Storm (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Juuryoku Soukou Metal Storm (J).nes"
if not EXIST "1133a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1133a.png"
if not EXIST "Solomon's Key 2 (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Solomon's Key 2 (E) [!].nes"
if not EXIST "2039a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2039a.png"
if not EXIST "Kings of the Beach (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Kings of the Beach (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Soccer (JU) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Soccer (JU) [!].nes"
if not EXIST "1223a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1223a.png"
if not EXIST "Empire Strikes Back, The (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Empire Strikes Back, The (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Akumajou Dracula (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Akumajou Dracula (J) [!].nes"
if not EXIST "87a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/87a.png"
if not EXIST "B-Wings (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/B-Wings (J) [!].nes"
if not EXIST "151a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/151a.png"
if not EXIST "Metal Storm (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Metal Storm (U) [!].nes"
if not EXIST "1432a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1432a.png"
if not EXIST "Fire 'n Ice (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Fire 'n Ice (U) [!].nes"
if not EXIST "764a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/764a.png"
if not EXIST "Venice Beach Volleyball (AVE) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Venice Beach Volleyball (AVE) [!].nes"
if not EXIST "2424a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2424a.png"
if not EXIST "Top Striker (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Top Striker (J).nes"
if not EXIST "2343a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2343a.png"
if not EXIST "Star Wars - The Empire Strikes Back (U) (Prototype) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Star Wars - The Empire Strikes Back (U) (Prototype) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Castlevania (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania (E) [!].nes"
if not EXIST "359a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/359a.png"
if not EXIST "Section-Z (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Section-Z (E) [!].nes"
if not EXIST "1926a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1926a.png"
if not EXIST "Metal Flame Psybuster (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Metal Flame Psybuster (J).nes"
if not EXIST "1425a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1425a.png"
if not EXIST "Hit Mouse (Unl).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Hit Mouse (Unl).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Superstar Pro Wrestling (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Superstar Pro Wrestling (J).nes"
if not EXIST "2187a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2187a.png"
if not EXIST "Mario Open Golf (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Mario Open Golf (J).nes"
if not EXIST "1374a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1374a.png"
if not EXIST "Xing Ji Zheng Ba (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Xing Ji Zheng Ba (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Castlevania (U) (PRG1) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania (U) (PRG1) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Section-Z (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Section-Z (U) [!].nes"
if not EXIST "1926a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1926a.png"
if not EXIST "Metal Mech - Man & Machine (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Metal Mech - Man & Machine (U) [!].nes"
if not EXIST "1430a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1430a.png"
if not EXIST "Family Block (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Family Block (J).nes"
if not EXIST "698a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/698a.png"
if not EXIST "WCW World Championship Wrestling (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WCW World Championship Wrestling (U) [!].nes"
if not EXIST "2452a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2452a.png"
if not EXIST "NES Open Tournament Golf (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/NES Open Tournament Golf (U) [!].nes"
if not EXIST "1551a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1551a.png"
if not EXIST "SG.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/SG.nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Castlevania II - Simon's Quest (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania II - Simon's Quest (E) [!].nes"
if not EXIST "359a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/359a.png"
if not EXIST "Silkworm (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Silkworm (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Great Tank (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Great Tank (J).nes"
if not EXIST "903a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/903a.png"
if not EXIST "Thunder & Lightning (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Thunder & Lightning (U) [!].nes"
if not EXIST "2295a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2295a.png"
if not EXIST "WWF WrestleMania Challenge (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF WrestleMania Challenge (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Namco Classic (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Namco Classic (J).nes"
if not EXIST "1535a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1535a.png"
if not EXIST "Chuuka Taisen (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Chuuka Taisen (J).nes"
if not EXIST "410a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/410a.png"
if not EXIST "Iron Tank (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Iron Tank (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Jongbou (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Jongbou (J) [!].nes"
if not EXIST "1111a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/1111a.png"
if not EXIST "WWF WrestleMania Challenge (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF WrestleMania Challenge (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Namco Classic 2 (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Namco Classic 2 (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Diablo (NJ037) (Ch).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/Diablo (NJ037) (Ch).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Castlevania II - Simon's Quest (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania II - Simon's Quest (U) [!].nes"
if not EXIST "360a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/360a.png"
if not EXIST "TwinBee (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/TwinBee (J) [!].nes"
if not EXIST "2382a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2382a.png"
if not EXIST "Predator (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Predator (J).nes"
if not EXIST "1711a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1711a.png"
if not EXIST "Arkanoid (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Arkanoid (J).nes"
if not EXIST "117a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/117a.png"
if not EXIST "WWF WrestleMania - Steel Cage Challenge (E).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF WrestleMania - Steel Cage Challenge (E).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Bandai Golf - Challenge Pebble Beach (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Bandai Golf - Challenge Pebble Beach (U) [!].nes"
if not EXIST "177a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/177a.png"
if not EXIST "[NJ065] Zui You Ji Zhi Tang San Zang.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ065] Zui You Ji Zhi Tang San Zang.nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Akumajou Densetsu (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Akumajou Densetsu (J) [!].nes"
if not EXIST "86a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/86a.png"
if not EXIST "Moero TwinBee - Cinnamon Hakase wo Sukue! (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Moero TwinBee - Cinnamon Hakase wo Sukue! (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Predator (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Predator (U) [!].nes"
if not EXIST "1712a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1712a.png"
if not EXIST "Arkanoid (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Arkanoid (U) [!].nes"
if not EXIST "118a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/118a.png"
if not EXIST "WWF WrestleMania - Steel Cage Challenge (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF WrestleMania - Steel Cage Challenge (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Jumbo Ozaki no Hole in One Professional (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Jumbo Ozaki no Hole in One Professional (J).nes"
if not EXIST "1124a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1124a.png"
if not EXIST "Castlevania III - Dracula's Curse (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania III - Dracula's Curse (E) [!].nes"
if not EXIST "361a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/361a.png"
if not EXIST "Stinger (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/Stinger (U) [!].nes"
if not EXIST "2108a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/2108a.png"
if not EXIST "Silver Eagle (Sachen) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Silver Eagle (Sachen) [!].nes"
if not EXIST "1993a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1993a.png"
if not EXIST "Arkanoid II (J) (Prototype).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Arkanoid II (J) (Prototype).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "WWF WrestleMania (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF WrestleMania (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Fighting Golf (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Fighting Golf (J).nes"
if not EXIST "749a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/749a.png"
if not EXIST "Castlevania III - Dracula's Curse (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Castlevania III - Dracula's Curse (U) [!].nes"
if not EXIST "362a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/362a.png"
if not EXIST "TwinBee 3 - Poko Poko Dai Maou (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/TwinBee 3 - Poko Poko Dai Maou (J) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "AV Mei Shao Nv Zhan Shi (Unl).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/gd/AV Mei Shao Nv Zhan Shi (Unl).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Spy Hunter (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Spy Hunter (U) [!].nes"
if not EXIST "2067a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2067a.png"
if not EXIST "Arkanoid II (J) [o1].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Arkanoid II (J) [o1].nes"
if not EXIST "119a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/119a.png"
if not EXIST "WWF King of the Ring (U) [!p].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/WWF King of the Ring (U) [!p].nes"
if not EXIST "2508a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2508a.png"
if not EXIST "Lee Trevino's Fighting Golf (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Lee Trevino's Fighting Golf (U) [!].nes"
if not EXIST "1246a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/1246a.png"
if not EXIST "Akumajou Special - Boku Dracula-kun (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Akumajou Special - Boku Dracula-kun (J) [!].nes"
if not EXIST "88a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/88a.png"
if not EXIST "TwinBee 3 - Poko Poko Dai Maou (J) [T+Chi_MS emumax].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/fxsj/TwinBee 3 - Poko Poko Dai Maou (J) [T+Chi_MS emumax].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Thundercade (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Thundercade (U) [!].nes"
if not EXIST "2299a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2299a.png"
if not EXIST "Titan (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Titan (J).nes"
if not EXIST "2318a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/2318a.png"
if not EXIST "Gekitou Pro Wrestling!! - Toukon Densetsu (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Gekitou Pro Wrestling!! - Toukon Densetsu (J).nes"
if not EXIST "840a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/840a.png"
if not EXIST "hdl1hh.nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/hdl1hh.nes"
if not EXIST "436a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/436a.png"
if not EXIST "Dragon Fighter (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Dragon Fighter (J).nes"
if not EXIST "596a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/596a.png"
if not EXIST "Super Turrican (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Super Turrican (E) [!].nes"
if not EXIST "2183a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/2183a.png"
if not EXIST "Cybernoid - The Fighting Machine (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Cybernoid - The Fighting Machine (U) [!].nes"
if not EXIST "462a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/462a.png"
if not EXIST "Exciting Boxing (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Exciting Boxing (J).nes"
if not EXIST "668a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/668a.png"
if not EXIST "Goal! Two (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Goal! Two (U) [!].nes"
if not EXIST "863a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/863a.png"
if not EXIST "[NJ006] Shu Ma Zhan Dui II (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/[NJ006] Shu Ma Zhan Dui II (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Choujin Sentai - Jetman (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Choujin Sentai - Jetman (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Layla (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Layla (J) [!].nes"
if not EXIST "1244a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1244a.png"
if not EXIST "Ninja Kun (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Ninja Kun (J).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Family Trainer 7 - Daiundoukai (J) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Family Trainer 7 - Daiundoukai (J) [!].nes"
if not EXIST "720a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/720a.png"
if not EXIST "Tecmo Bowl (J).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/Tecmo Bowl (J).nes"
if not EXIST "2238a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/ydbs/2238a.png"
if not EXIST "You Ling Lie Che (ES-1108) (C).nes" wget --no-check-certificate "https://file.1990i.com//fcrom/jsbyzw/You Ling Lie Che (ES-1108) (C).nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Shadow Warriors Episode II - The Dark Sword of Chaos (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Shadow Warriors Episode II - The Dark Sword of Chaos (E) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Choujin Sentai - Jetman (J) [T+Chi].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Choujin Sentai - Jetman (J) [T+Chi].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Mission - Impossible (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Mission - Impossible (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Cabal (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Cabal (U) [!].nes"
if not EXIST "325a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/325a.png"
if not EXIST "Pinball Quest (E) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Pinball Quest (E) [!].nes"
if not EXIST "1682a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/1682a.png"
if not EXIST "10-Yard Fight (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/ydbs/10-Yard Fight (U) [!].nes"
if not EXIST "1000a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/1000a.png"
if not EXIST "Conquest of the Crystal Palace (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/dzmx/Conquest of the Crystal Palace (U) [!].nes"
if not EXIST "435a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/435a.png"
if not EXIST "Punisher, The (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/sj/Punisher, The (U) [!].nes"
if not EXIST "1739a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/sj/1739a.png"
if not EXIST "Pinball Quest (U) [!].nes" wget --no-check-certificate "https://file.1990i.com//fcrom/xyx/Pinball Quest (U) [!].nes"
if not EXIST "1682a.png" wget --no-check-certificate "https://img.1990i.com/fcpic/xyx/1682a.png"