name: Build Vue Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build vue project "prj1"
        working-directory: ./prj1
        run: |
          yarn install
          yarn build
      - name: build vue project "prj2"
        working-directory: ./prj2
        run: |
          yarn install
          yarn build
      - name: Commit to special path
        run: |
          mv ./prj1/dist ./prj1_view
          mv ./prj2/dist ./prj2_view
          rm -rf ./prj1
          rm -rf ./prj2
          git checkout -b views
          git add .
          git commit -m "build"
          git config --global user.email "1134098699@qq.com"
          git push